### ISSUE TITLE
ionic2 example: impossible to execute command ionic run android

### ISSUE THREAD

**Issue by marianoc84** [dpa99c/phonegap-launch-navigator-example#6]
I need to use `launchnavigator `in a personal project, but, alas I encounter some problem. So I tried starting from an official example. I've downloaded  the repository go inside `Ionic2Example` directory and tried the following command as specified in the readme:

`npm install` some WARN and Avira that inform me about `ExpKit.Gen2`. It's OK?

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @ionic/storage@1.1.9 requires a peer of @angular/core@* but none was installed.
npm WARN ionic-angular@2.1.0 requires a peer of @angular/common@2.2.1 but none was installed.
npm WARN ionic-angular@2.1.0 requires a peer of @angular/compiler@2.2.1 but none was installed.
npm WARN ionic-angular@2.1.0 requires a peer of @angular/compiler-cli@2.2.1 but none was installed.
npm WARN ionic-angular@2.1.0 requires a peer of @angular/core@2.2.1 but none was installed.
npm WARN ionic-angular@2.1.0 requires a peer of @angular/forms@2.2.1 but none was installed.
npm WARN ionic-angular@2.1.0 requires a peer of @angular/http@2.2.1 but none was installed.
npm WARN ionic-angular@2.1.0 requires a peer of @angular/platform-browser@2.2.1 but none was installed.
npm WARN ionic-angular@2.1.0 requires a peer of @angular/platform-browser-dynamic@2.2.1 but none was installed.
npm WARN ionic-angular@2.1.0 requires a peer of @angular/platform-server@2.2.1 but none was installed.
npm WARN ionic-angular@2.1.0 requires a peer of zone.js@~0.6.26 but none was installed.
npm WARN @ionic/app-scripts@1.1.4 requires a peer of @angular/core@* but none was installed.
npm WARN @ionic/app-scripts@1.1.4 requires a peer of @angular/compiler@* but none was installed.
npm WARN @ionic/app-scripts@1.1.4 requires a peer of @angular/compiler-cli@* but none was installed.
npm WARN @ionic/app-scripts@1.1.4 requires a peer of @angular/tsc-wrapped@* but none was installed.
npm WARN @ionic/app-scripts@1.1.4 requires a peer of sw-toolbox@* but none was installed.
npm WARN @ionic/app-scripts@1.1.4 requires a peer of zone.js@* but none was installed.
npm WARN launchnavigator.ionic2example@3.2.0 No repository field.
npm WARN launchnavigator.ionic2example@3.2.0 No license field.
```

the commands `ionic state restore` and `ionic add platform android` seems to go like charm, but the last command `ionic run android` goes in error, see below:

```
Running 'run:before' npm script before run
> launchnavigator.ionic2example@3.2.0 build C:\Users\Mariano\Desktop\phonegap-launch-navigator-example-master\Ionic2Example
> ionic-app-scripts build
module.js:471
    throw err;
    ^

Error: Cannot find module 'reflect-metadata'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Mariano\Desktop\phonegap-launch-navigator-example-master\Ionic2Example\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:4:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)



npm
 ERR! Windows_NT 10.0.14393
npm ERR!
 argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node
 v6.9.5
npm ERR! npm  v3.10.10

npm
 ERR! code ELIFECYCLE
npm
 ERR! launchnavigator.ionic2example@3.2.0 build: `ionic-app-scripts build`
npm
 ERR! Exit status 1
npm ERR!

npm ERR! Failed at the launchnavigator.ionic2example@3.2.0 build script 'ionic-app-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

npm ERR! If you do, this is most likely a problem with the launchnavigator.ionic2example package,
npm ERR! not with npm itself.

npm
ERR! Tell the author that this fails on your system:
npm
 ERR!
     ionic-app-scripts build
npm ERR!
 You can get information on how to open an issue for this project with:
npm ERR!     npm bugs launchnavigator.ionic2example
npm ERR!
 Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls launchnavigator.ionic2example
npm
ERR! There is likely additional logging output above.



npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Mariano\Desktop\phonegap-launch-navigator-example-master\Ionic2Example\npm-debug.log

Caught exception:
 undefined
```

I know.. I oculd installl `reflect-metadata` and every other requested package but this going forward with this "hacky" solution doesn't seems the right way. what happens?

My conf:
npm@3.10.10
node@v6.9.5

**Comment by dpa99c** [comment]
The Ionic2Example hasn't been updated for almost 1/2 year, so the build error is probably because the build configuration is [referencing an old version of the framework](https://github.com/dpa99c/phonegap-launch-navigator-example/blob/master/Ionic2Example/package.json#L17) - I'll have a look and update the config if necessary.

> npm install some WARN and Avira that inform me about ExpKit.Gen2. It's OK?

WARNings are common in node modules and nothing to worry about

node modules contain only Javascript so the `ExpKit.Gen2` found by Avira is unrelated, though I would perform a full system scan on your computer for viruses.

**Comment by dpa99c** [comment]
I've updated the Ionic2Example project to work with Ionic 2 FINAL. Best thing to wipe your local copy, clone again, then run `npm install && ionic state restore && ionic serve` - should work fine
